# Generated by Django 2.1.7 on 2019-03-06 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='genres',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='leaderboards',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='questions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ques', models.CharField(max_length=200)),
                ('optA', models.TextField()),
                ('optB', models.TextField()),
                ('optC', models.TextField()),
                ('optD', models.TextField()),
                ('correctopt', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='states',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qno', models.IntegerField(default=0)),
                ('score', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='subgenre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cont', models.TextField()),
                ('genre_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.genres')),
            ],
        ),
        migrations.CreateModel(
            name='users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('password_digest', models.TextField()),
                ('remember_digest', models.TextField()),
                ('admin', models.BooleanField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='states',
            name='subgenre_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.subgenre'),
        ),
        migrations.AddField(
            model_name='states',
            name='users_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.users'),
        ),
        migrations.AddField(
            model_name='questions',
            name='subgenre_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.subgenre'),
        ),
        migrations.AddField(
            model_name='leaderboards',
            name='subgenre_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.subgenre'),
        ),
        migrations.AddField(
            model_name='leaderboards',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.users'),
        ),
    ]
