# Generated by Django 2.1.7 on 2019-03-08 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_auto_20190308_1639'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='password_digest',
            field=models.CharField(default=2, max_length=32),
            preserve_default=False,
        ),
    ]
